import Head from 'next/head'
import Lorem from '../components/lorem'
import HomeLayout from '../layouts/homeLayout'
import { globalStyles } from '../styles/globals'
import { textLink } from '../styles/mixins'
import { css } from '../stitches.config'


export default function Home() {
  globalStyles()

  return (
    <HomeLayout>
      <Head>
        <title>Cassidy Smith | Front-End Engineer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={css({
        a: textLink,
      })()}>
        <h1>Hello!</h1>
        <p>Welcome to my home page =) I’m Cassidy as you probably guessed. This site is under construction 🚧 I’m a front-end engineer and UI designer full-time at <a href="https://nobledesktop.com" target='_blank' rel='noopener noreferrer'>Noble Desktop</a>. I enjoy creative and intentional problem solving with code. Day-to-day I work in Ruby on Rails, JavaScript/ES6, Next.js, React, CSS, and HTML, but I love to explore new frameworks, languages, and tools.</p>
        <p>Other than work stuff, I hope to make this website a place for digital art. My current obsession is <a href="https://en.wikipedia.org/wiki/Creative_coding" target="_blank" rel="noopener noreferrer">Generative Art / Creative Coding</a> and I’m working on series of randomly-generated, single-edition, cactus-inspired art prints with <a href="http://paperjs.org/" target="_blank" rel="noopener noreferrer">Paper.js</a>. Stay tuned for more!</p>

        

        
        
        {/* <Lorem /> */}


      </main>

    </HomeLayout>
  )
}
