import Head from 'next/head'
import Lorem from '../components/lorem'
import HomeLayout from '../layouts/homeLayout'
import { globalStyles } from '../styles/globals'
import { textLink } from '../styles/mixins'
import { css } from '../stitches.config'

export default function Home() {
  globalStyles()

  return (
    <HomeLayout>
      <Head>
        <title>Cassidy Smith | Front-End Engineer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={css({
        a: textLink,
        maxWidth: '60ch'
      })()}>
        <h1>Hello!</h1>
      
        <p>
        Hi, I’m Cassidy. I’m a front-end engineer and web designer at <a href="https://nobledesktop.com" rel='noopener noreferrer'>Noble Desktop</a>. I mostly do front-end development and design, but also work up and down the Rails stack.
        </p>
        <p>
        Call me Cass-cading Style Sheets (ba-dum-tss), but CSS is more than a bad joke to me. I’ve been writing the stuff for 5+ years and I love how enjoyable and powerful modern CSS can be. I also love to write JavaScript, Ruby and whatever else I can get my hands on.
        </p>
        {/* <Lorem /> */}


      </main>

    </HomeLayout>
  )
}
